### First Data Check

In [16]:
import pandas as pd

df = pd.read_csv("../data/air_pollution.csv", sep=";")

df.head()

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,JP,NaN,北九州市小倉北区大門一丁目６－４８,"33.880833, 130.873056",NO,japan-soramame,ppm,0.002,2024-03-10T13:30:00+05:30,Japan
1,JP,NaN,北九州市若松区本町三丁目１３－１,"33.898056, 130.81",NO2,japan-soramame,ppm,0.005,2024-03-10T13:30:00+05:30,Japan
2,JP,NaN,北九州市門司区大里原町１２－１２,"33.895833, 130.935833",NOX,japan-soramame,ppm,0.013,2024-03-10T13:30:00+05:30,Japan
3,JP,NaN,千歳市若草４－１３,"42.786944, 141.605",NO2,japan-soramame,ppm,0.004,2024-03-10T13:30:00+05:30,Japan
4,JP,NaN,千葉市稲毛区宮野木町９９６－９,"35.653889, 140.097778",NOX,japan-soramame,ppm,0.003,2024-03-10T13:30:00+05:30,Japan

In [17]:
df.columns

Index(['Country Code', 'City', 'Location', 'Coordinates', 'Pollutant',
       'Source Name', 'Unit', 'Value', 'Last Updated', 'Country Label'],
      dtype='object')

### Cleaning the Dataset

In [18]:
# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['country_code', 'city', 'location', 'coordinates', 'pollutant',
       'source_name', 'unit', 'value', 'last_updated', 'country_label'],
      dtype='object')

In [24]:
# Keeping only relevant columns
df = df[['city', 'country_label', 'coordinates', 'pollutant', 'value', 'last_updated']]
df.head()

,city,country_label,coordinates,pollutant,value,last_updated
0,NaN,Japan,"33.880833, 130.873056",NO,0.002,2024-03-10T13:30:00+05:30
1,NaN,Japan,"33.898056, 130.81",NO2,0.005,2024-03-10T13:30:00+05:30
2,NaN,Japan,"33.895833, 130.935833",NOX,0.013,2024-03-10T13:30:00+05:30
3,NaN,Japan,"42.786944, 141.605",NO2,0.004,2024-03-10T13:30:00+05:30
4,NaN,Japan,"35.653889, 140.097778",NOX,0.003,2024-03-10T13:30:00+05:30

In [25]:
# Filter for PM2.5 pollutant
df = df[df['pollutant'] == 'PM2.5']
df.head()

,city,country_label,coordinates,pollutant,value,last_updated
6,NaN,Japan,"36.027222, 139.716111",PM2.5,2.0,2024-03-10T13:30:00+05:30
13,NaN,Japan,"35.073056, 136.916667",PM2.5,3.0,2024-03-10T13:30:00+05:30
16,NaN,Japan,"35.319444, 140.056667",PM2.5,5.0,2024-03-10T13:30:00+05:30
28,NaN,Japan,"35.305833, 137.170278",PM2.5,3.0,2024-03-10T13:30:00+05:30
42,NaN,Japan,"34.781944, 134.7075",PM2.5,7.0,2024-03-10T13:30:00+05:30

In [27]:
# Rename columns
df = df.rename(columns={
    'country_label': 'country',
    'value': 'pm25'
})

df.head()

,city,country,coordinates,pollutant,pm25,last_updated
6,NaN,Japan,"36.027222, 139.716111",PM2.5,2.0,2024-03-10T13:30:00+05:30
13,NaN,Japan,"35.073056, 136.916667",PM2.5,3.0,2024-03-10T13:30:00+05:30
16,NaN,Japan,"35.319444, 140.056667",PM2.5,5.0,2024-03-10T13:30:00+05:30
28,NaN,Japan,"35.305833, 137.170278",PM2.5,3.0,2024-03-10T13:30:00+05:30
42,NaN,Japan,"34.781944, 134.7075",PM2.5,7.0,2024-03-10T13:30:00+05:30

In [28]:
# Extract latitude and longitude from coordinates
df[['latitude', 'longitude']] = df['coordinates'].str.split(',', expand=True).astype(float)
df.head()

,city,country,coordinates,pollutant,pm25,last_updated,latitude,longitude
6,NaN,Japan,"36.027222, 139.716111",PM2.5,2.0,2024-03-10T13:30:00+05:30,36.027222,139.716111
13,NaN,Japan,"35.073056, 136.916667",PM2.5,3.0,2024-03-10T13:30:00+05:30,35.073056,136.916667
16,NaN,Japan,"35.319444, 140.056667",PM2.5,5.0,2024-03-10T13:30:00+05:30,35.319444,140.056667
28,NaN,Japan,"35.305833, 137.170278",PM2.5,3.0,2024-03-10T13:30:00+05:30,35.305833,137.170278
42,NaN,Japan,"34.781944, 134.7075",PM2.5,7.0,2024-03-10T13:30:00+05:30,34.781944,134.707500

In [29]:
# Drop the original coordinates column
df = df.drop(columns=['coordinates'])
df.head()

,city,country,pollutant,pm25,last_updated,latitude,longitude
6,NaN,Japan,PM2.5,2.0,2024-03-10T13:30:00+05:30,36.027222,139.716111
13,NaN,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.073056,136.916667
16,NaN,Japan,PM2.5,5.0,2024-03-10T13:30:00+05:30,35.319444,140.056667
28,NaN,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.305833,137.170278
42,NaN,Japan,PM2.5,7.0,2024-03-10T13:30:00+05:30,34.781944,134.707500

In [30]:
# Replacing missing cities with 'Unknown Location'
df['city'] = df['city'].fillna('Unknown Location')
df.head()

,city,country,pollutant,pm25,last_updated,latitude,longitude
6,Unknown Location,Japan,PM2.5,2.0,2024-03-10T13:30:00+05:30,36.027222,139.716111
13,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.073056,136.916667
16,Unknown Location,Japan,PM2.5,5.0,2024-03-10T13:30:00+05:30,35.319444,140.056667
28,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.305833,137.170278
42,Unknown Location,Japan,PM2.5,7.0,2024-03-10T13:30:00+05:30,34.781944,134.707500

In [31]:
# Removing missing values
df = df.dropna(subset=['latitude', 'longitude', 'pm25'])
df.head()

,city,country,pollutant,pm25,last_updated,latitude,longitude
6,Unknown Location,Japan,PM2.5,2.0,2024-03-10T13:30:00+05:30,36.027222,139.716111
13,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.073056,136.916667
16,Unknown Location,Japan,PM2.5,5.0,2024-03-10T13:30:00+05:30,35.319444,140.056667
28,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.305833,137.170278
42,Unknown Location,Japan,PM2.5,7.0,2024-03-10T13:30:00+05:30,34.781944,134.707500

In [32]:
# Removing outliers in PM values
df = df[(df['pm25']> 0) & (df['pm25'] < 500)]
df.head()

,city,country,pollutant,pm25,last_updated,latitude,longitude
6,Unknown Location,Japan,PM2.5,2.0,2024-03-10T13:30:00+05:30,36.027222,139.716111
13,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.073056,136.916667
16,Unknown Location,Japan,PM2.5,5.0,2024-03-10T13:30:00+05:30,35.319444,140.056667
28,Unknown Location,Japan,PM2.5,3.0,2024-03-10T13:30:00+05:30,35.305833,137.170278
42,Unknown Location,Japan,PM2.5,7.0,2024-03-10T13:30:00+05:30,34.781944,134.707500

## Final Check

In [33]:
df.describe()

              pm25     latitude    longitude
count  9136.000000  9136.000000  9136.000000
mean     18.771684    33.508919    25.067389
std      30.732073    19.595341    91.337609
min       0.039000   -74.166278  -161.767000
25%       5.200000    30.038961   -73.609620
50%      11.000000    37.178000    19.902090
75%      20.000000    44.742812   113.989250
max     472.460000    70.131900   174.780000

## Basic Map

In [34]:
import plotly.express as px

fig = px.scatter_geo(df, lat='latitude', lon='longitude', color='pm25',
                     size='pm25', hover_name='country', projection='natural earth',
                        title='Global PM2.5 Pollution Levels')

fig.show()

## Improved Map

In [38]:
fig = px.scatter_geo(df, lat='latitude', lon='longitude', color='pm25',
                     size='pm25', hover_name='country', projection='natural earth',
                        title='Global PM2.5 Pollution Levels')

fig.update_layout(geo=dict(showland=True, landcolor='rgb(243, 243, 243)', showcountries=True),
                  margin={"r":0,"t":50,"l":0,"b":0})

fig.show()

### First Insights

In [44]:
# Top polluted countries
top_countries = df.groupby('country')['pm25'].mean().sort_values(ascending=False).head(10)
print(top_countries)

country
Singapore               282.900000
Afghanistan             136.000000
Ghana                   121.124928
Kazakhstan              116.500000
Mongolia                111.054545
India                    94.106409
Saudi Arabia             80.464600
Algeria                  78.000000
United Arab Emirates     60.733333
Bangladesh               60.350000
Name: pm25, dtype: float64

In [47]:
# Plotting the result
fig = px.bar(top_countries, x=top_countries.values, y=top_countries.index, orientation='h',
                 title='Top 10 Most Polluted Countries by Average PM2.5 Levels',
                 labels={'x': 'Average PM2.5 Level', 'y': 'Country'})

fig.show()

## Export Clean Dataframe

In [48]:
df.to_csv("../data/cleaned_air_pollution.csv", index=False)